name: Run

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama serve &
          sleep 5
          ollama run phi3 "Hello, who are you?"
