name: Run

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -L https://ollama.com/download/ollama-linux-amd64 -o ./ollama
          chmod +x ./ollama
          ./ollama serve &
          sleep 5
          ./ollama run llama3.2:1b "Explain the following code: $(cat .github/workflows/run.yml)"
